# Hi!

# This file customizes a web page template with your info.
# Type in the appropriate info items below

# Lines of text that begin with # are COMMENTS.

# Comments are ignored by the software that feeds your info below
# into the web page template.

# This file is a part of the HSHSL workshop Using GitHub to Manage Your Scholarly Work.

name: Brian Zelip
email: bzelip@gmail.com
job_title: Emerging Tech Librarian
degrees: ["MA","MS"] # type your degrees inside the square brackets in quotes and separated by a comma, ie: ["BA","MS","Ph.D"]
institution_name: University of Maryland
institution_URL: http://umaryland.edu
department_name: Healt Sciences and Human Services Library
department_URL: http://www.hshsl.umaryland.edu
github_username: brianzelip
twitter_username: bzelip
linkedin_URL: 
selfie_URL: https://pbs.twimg.com/profile_images/600705601165856769/O6TyOOQd_400x400.jpg

social:
  have_twitter: true
  have_linkedin: false

# Technical configuration
markdown: kramdown
permalinks: pretty
